손글씨

In [1]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
import numpy as np

In [3]:
digits = load_digits()

In [5]:
digits_label = digits.target
print(digits_label)

[0 1 2 ... 8 9 8]


In [6]:
print(digits.target_names)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
digits_images = digits.images
print(digits_images[0])

[[ 0.  0.  5. 13.  9.  1.  0.  0.]
 [ 0.  0. 13. 15. 10. 15.  5.  0.]
 [ 0.  3. 15.  2.  0. 11.  8.  0.]
 [ 0.  4. 12.  0.  0.  8.  8.  0.]
 [ 0.  5.  8.  0.  0.  9.  8.  0.]
 [ 0.  4. 11.  0.  1. 12.  7.  0.]
 [ 0.  2. 14.  5. 10. 12.  0.  0.]
 [ 0.  0.  6. 13. 10.  0.  0.  0.]]


In [8]:
x_train, x_test, y_train, y_test = train_test_split(digits_data, digits_label, test_size=0.3, random_state=30)

In [10]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(1257, 64) (1257,)
(540, 64) (540,)


In [62]:
from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier(random_state=30)
print(decision_tree._estimator_type)
print('DecisionTreeClassifier 분류 모델이다.')

decision_tree.fit(x_train, y_train)

y_pred_decision = decision_tree.predict(x_test)

print('\n')
print('정답률 :', accuracy_score(y_test, y_pred_decision))

print('\n')
print(classification_report(y_test, y_pred_decision))

classifier
DecisionTreeClassifier 분류 모델이다.


정답률 : 0.9298245614035088


              precision    recall  f1-score   support

           0       0.89      0.92      0.90        62
           1       0.95      0.94      0.94       109

    accuracy                           0.93       171
   macro avg       0.92      0.93      0.92       171
weighted avg       0.93      0.93      0.93       171



In [61]:
from sklearn.ensemble import RandomForestClassifier

random_forest = RandomForestClassifier(random_state=30)
print(random_forest._estimator_type)
print('RandomForestClassifier 분류 모델이다.')

random_forest.fit(x_train, y_train)

y_pred_random = random_forest.predict(x_test)

print('\n')
print('정답률 :', accuracy_score(y_test, y_pred_random))

print('\n')
print(classification_report(y_test, y_pred_random))

classifier
RandomForestClassifier 분류 모델이다.


정답률 : 0.9649122807017544


              precision    recall  f1-score   support

           0       0.98      0.92      0.95        62
           1       0.96      0.99      0.97       109

    accuracy                           0.96       171
   macro avg       0.97      0.96      0.96       171
weighted avg       0.97      0.96      0.96       171



In [16]:
import sklearn.svm as svm

svm = svm.SVC()
print(svm._estimator_type)
print('Support Vector Machine 분류 모델이다.')

svm.fit(x_train, y_train)

y_pred_svm = svm.predict(x_test)

print('\n')
print('정답률 :', accuracy_score(y_test, y_pred_svm))

print('\n')
print(classification_report(y_test, y_pred_svm))

classifier
Support Vector Machine 분류 모델이다.


정답률 : 0.9851851851851852


              precision    recall  f1-score   support

           0       1.00      0.98      0.99        58
           1       0.98      1.00      0.99        57
           2       0.98      1.00      0.99        61
           3       0.98      0.96      0.97        45
           4       0.98      0.98      0.98        58
           5       0.98      1.00      0.99        55
           6       1.00      0.98      0.99        60
           7       1.00      1.00      1.00        49
           8       0.96      0.98      0.97        49
           9       0.98      0.96      0.97        48

    accuracy                           0.99       540
   macro avg       0.98      0.98      0.98       540
weighted avg       0.99      0.99      0.99       540



In [17]:
from sklearn.linear_model import SGDClassifier

sgd = SGDClassifier()
print(sgd._estimator_type)
print('Stochastic Gradient Descent 분류 모델이다.')

sgd.fit(x_train, y_train)

y_pred_sgd = sgd.predict(x_test)

print('\n')
print('정답률 :', accuracy_score(y_test, y_pred_sgd))

print('\n')
print(classification_report(y_test, y_pred_sgd))

classifier
Stochastic Gradient Descent 분류 모델이다.


정답률 : 0.9537037037037037


              precision    recall  f1-score   support

           0       1.00      0.97      0.98        58
           1       0.91      0.93      0.92        57
           2       0.97      1.00      0.98        61
           3       0.93      0.91      0.92        45
           4       0.98      0.98      0.98        58
           5       0.98      0.93      0.95        55
           6       0.97      0.98      0.98        60
           7       0.98      1.00      0.99        49
           8       0.90      0.88      0.89        49
           9       0.90      0.94      0.92        48

    accuracy                           0.95       540
   macro avg       0.95      0.95      0.95       540
weighted avg       0.95      0.95      0.95       540



In [63]:
from sklearn.linear_model import LogisticRegression

logistic = LogisticRegression(max_iter=10000)
print(logistic._estimator_type)
print('LogisticRegression 분류 모델이다.')

logistic.fit(x_train, y_train)

y_pred_logistic = logistic.predict(x_test)

from sklearn.metrics import accuracy_score
print('\n')
print('정답률 :', accuracy_score(y_test, y_pred_logistic))

print('\n')
print(classification_report(y_test, y_pred_logistic))

classifier
LogisticRegression 분류 모델이다.


정답률 : 0.9239766081871345


              precision    recall  f1-score   support

           0       0.92      0.87      0.89        62
           1       0.93      0.95      0.94       109

    accuracy                           0.92       171
   macro avg       0.92      0.91      0.92       171
weighted avg       0.92      0.92      0.92       171



와인

In [23]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [24]:
wine = load_wine()

In [25]:
wine_data = wine.data
print(wine_data)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [26]:
wine_label = wine.target
print(wine_label)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [29]:
print(wine.target_names)

['class_0' 'class_1' 'class_2']


In [30]:
digits_images = digits.images
print(digits_images[0])

[[ 0.  0.  5. 13.  9.  1.  0.  0.]
 [ 0.  0. 13. 15. 10. 15.  5.  0.]
 [ 0.  3. 15.  2.  0. 11.  8.  0.]
 [ 0.  4. 12.  0.  0.  8.  8.  0.]
 [ 0.  5.  8.  0.  0.  9.  8.  0.]
 [ 0.  4. 11.  0.  1. 12.  7.  0.]
 [ 0.  2. 14.  5. 10. 12.  0.  0.]
 [ 0.  0.  6. 13. 10.  0.  0.  0.]]


In [31]:
x_train, x_test, y_train, y_test = train_test_split(wine_data, wine_label, test_size=0.3, random_state=30)

In [32]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(124, 13) (124,)
(54, 13) (54,)


In [64]:
from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier(random_state=30)
print(decision_tree._estimator_type)
print('DecisionTreeClassifier 분류 모델이다.')

decision_tree.fit(x_train, y_train)

y_pred_decision = decision_tree.predict(x_test)

print('\n')
print('정답률 :', accuracy_score(y_test, y_pred_decision))

print('\n')
print(classification_report(y_test, y_pred_decision))

classifier
DecisionTreeClassifier 분류 모델이다.


정답률 : 0.9298245614035088


              precision    recall  f1-score   support

           0       0.89      0.92      0.90        62
           1       0.95      0.94      0.94       109

    accuracy                           0.93       171
   macro avg       0.92      0.93      0.92       171
weighted avg       0.93      0.93      0.93       171



In [65]:
from sklearn.ensemble import RandomForestClassifier

random_forest = RandomForestClassifier(random_state=30)
print(random_forest._estimator_type)
print('RandomForestClassifier 분류 모델이다.')

random_forest.fit(x_train, y_train)

y_pred_random = random_forest.predict(x_test)

print('\n')
print('정답률 :', accuracy_score(y_test, y_pred_random))

print('\n')
print(classification_report(y_test, y_pred_random))

classifier
RandomForestClassifier 분류 모델이다.


정답률 : 0.9649122807017544


              precision    recall  f1-score   support

           0       0.98      0.92      0.95        62
           1       0.96      0.99      0.97       109

    accuracy                           0.96       171
   macro avg       0.97      0.96      0.96       171
weighted avg       0.97      0.96      0.96       171



In [35]:
import sklearn.svm as svm

svm = svm.SVC()
print(svm._estimator_type)
print('Support Vector Machine 분류 모델이다.')

svm.fit(x_train, y_train)

y_pred_svm = svm.predict(x_test)

print('\n')
print('정답률 :', accuracy_score(y_test, y_pred_svm))

print('\n')
print(classification_report(y_test, y_pred_svm))

classifier
Support Vector Machine 분류 모델이다.


정답률 : 0.7222222222222222


              precision    recall  f1-score   support

           0       0.93      0.78      0.85        18
           1       0.80      0.70      0.74        23
           2       0.47      0.69      0.56        13

    accuracy                           0.72        54
   macro avg       0.74      0.72      0.72        54
weighted avg       0.77      0.72      0.74        54



In [36]:
from sklearn.linear_model import SGDClassifier

sgd = SGDClassifier()
print(sgd._estimator_type)
print('Stochastic Gradient Descent 분류 모델이다.')

sgd.fit(x_train, y_train)

y_pred_sgd = sgd.predict(x_test)

print('\n')
print('정답률 :', accuracy_score(y_test, y_pred_sgd))

print('\n')
print(classification_report(y_test, y_pred_sgd))

classifier
Stochastic Gradient Descent 분류 모델이다.


정답률 : 0.5370370370370371


              precision    recall  f1-score   support

           0       0.73      0.89      0.80        18
           1       1.00      0.13      0.23        23
           2       0.34      0.77      0.48        13

    accuracy                           0.54        54
   macro avg       0.69      0.60      0.50        54
weighted avg       0.75      0.54      0.48        54



In [66]:
from sklearn.linear_model import LogisticRegression

logistic = LogisticRegression(max_iter=10000)
print(logistic._estimator_type)
print('LogisticRegression 분류 모델이다.')

logistic.fit(x_train, y_train)

y_pred_logistic = logistic.predict(x_test)

from sklearn.metrics import accuracy_score
print('\n')
print('정답률 :', accuracy_score(y_test, y_pred_logistic))

print('\n')
print(classification_report(y_test, y_pred_logistic))

classifier
LogisticRegression 분류 모델이다.


정답률 : 0.9239766081871345


              precision    recall  f1-score   support

           0       0.92      0.87      0.89        62
           1       0.93      0.95      0.94       109

    accuracy                           0.92       171
   macro avg       0.92      0.91      0.92       171
weighted avg       0.92      0.92      0.92       171



유방암

In [38]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [44]:
breast_cancer = load_breast_cancer()

In [45]:
breast_cancer_data = breast_cancer.data
print(breast_cancer_data)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [46]:
breast_cancer_label = breast_cancer.target
print(breast_cancer_label)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [48]:
print(breast_cancer.target_names)

['malignant' 'benign']


In [49]:
x_train, x_test, y_train, y_test = train_test_split(breast_cancer_data, breast_cancer_label, test_size=0.3, random_state=30)

In [50]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(398, 30) (398,)
(171, 30) (171,)


In [67]:
from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier(random_state=30)
print(decision_tree._estimator_type)
print('DecisionTreeClassifier 분류 모델이다.')

decision_tree.fit(x_train, y_train)

y_pred_decision = decision_tree.predict(x_test)

print('\n')
print('정답률 :', accuracy_score(y_test, y_pred_decision))

print('\n')
print(classification_report(y_test, y_pred_decision))

classifier
DecisionTreeClassifier 분류 모델이다.


정답률 : 0.9298245614035088


              precision    recall  f1-score   support

           0       0.89      0.92      0.90        62
           1       0.95      0.94      0.94       109

    accuracy                           0.93       171
   macro avg       0.92      0.93      0.92       171
weighted avg       0.93      0.93      0.93       171



In [68]:
from sklearn.ensemble import RandomForestClassifier

random_forest = RandomForestClassifier(random_state=30)
print(random_forest._estimator_type)
print('RandomForestClassifier 분류 모델이다.')

random_forest.fit(x_train, y_train)

y_pred_random = random_forest.predict(x_test)

print('\n')
print('정답률 :', accuracy_score(y_test, y_pred_random))

print('\n')
print(classification_report(y_test, y_pred_random))

classifier
RandomForestClassifier 분류 모델이다.


정답률 : 0.9649122807017544


              precision    recall  f1-score   support

           0       0.98      0.92      0.95        62
           1       0.96      0.99      0.97       109

    accuracy                           0.96       171
   macro avg       0.97      0.96      0.96       171
weighted avg       0.97      0.96      0.96       171



In [55]:
import sklearn.svm as svm

svm = svm.SVC()
print(svm._estimator_type)
print('Support Vector Machine 분류 모델이다.')

svm.fit(x_train, y_train)

y_pred_svm = svm.predict(x_test)

print('\n')
print('정답률 :', accuracy_score(y_test, y_pred_svm))

print('\n')
print(classification_report(y_test, y_pred_svm))

classifier
Support Vector Machine 분류 모델이다.


정답률 : 0.9122807017543859


              precision    recall  f1-score   support

           0       0.98      0.77      0.86        62
           1       0.89      0.99      0.94       109

    accuracy                           0.91       171
   macro avg       0.93      0.88      0.90       171
weighted avg       0.92      0.91      0.91       171



In [56]:
from sklearn.linear_model import SGDClassifier

sgd = SGDClassifier()
print(sgd._estimator_type)
print('Stochastic Gradient Descent 분류 모델이다.')

sgd.fit(x_train, y_train)

y_pred_sgd = sgd.predict(x_test)

print('\n')
print('정답률 :', accuracy_score(y_test, y_pred_sgd))

print('\n')
print(classification_report(y_test, y_pred_sgd))

classifier
Stochastic Gradient Descent 분류 모델이다.


정답률 : 0.9064327485380117


              precision    recall  f1-score   support

           0       0.98      0.76      0.85        62
           1       0.88      0.99      0.93       109

    accuracy                           0.91       171
   macro avg       0.93      0.87      0.89       171
weighted avg       0.91      0.91      0.90       171



In [57]:
logistic = LogisticRegression(max_iter=10000)
print(logistic._estimator_type)
print('LogisticRegression 분류 모델이다.')

logistic.fit(x_train, y_train)

y_pred_logistic = logistic.predict(x_test)

from sklearn.metrics import accuracy_score
print('\n')
print('정답률 :', accuracy_score(y_test, y_pred_logistic))

print('\n')
print(classification_report(y_test, y_pred_logistic))


classifier
LogisticRegression 분류 모델이다.


정답률 : 0.9239766081871345


              precision    recall  f1-score   support

           0       0.92      0.87      0.89        62
           1       0.93      0.95      0.94       109

    accuracy                           0.92       171
   macro avg       0.92      0.91      0.92       171
weighted avg       0.92      0.92      0.92       171



회고

처음 시도하는 프로젝트라서 매우 어려웠습니다. 